name: Publish

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '14.x'
        registry-url: 'https://registry.npmjs.org'
    - run: yarn install
    - run: yarn build
    - run: yarn test
    - run: npm publish
      working-directory: ./dist
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}